/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.17.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.api;

import org.openapitools.model.AdminShopPatch;
import org.openapitools.model.AuditLog;
import org.springframework.lang.Nullable;
import org.openapitools.model.Shop;
import java.util.UUID;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-11-02T12:30:08.264664900+07:00[Asia/Saigon]", comments = "Generator version: 7.17.0")
@Validated
@Tag(name = "admin", description = "the admin API")
public interface AdminApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    String PATH_ADMIN_AUDIT_GET = "/admin/audit";
    /**
     * GET /admin/audit : Audit logs (Admin)
     *
     * @param shopId  (optional)
     * @param actor  (optional)
     * @param action  (optional)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "adminAuditGet",
        summary = "Audit logs (Admin)",
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = AuditLog.class)))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = AdminApi.PATH_ADMIN_AUDIT_GET,
        produces = { "application/json" }
    )
    default ResponseEntity<List<AuditLog>> adminAuditGet(
        @Parameter(name = "shop_id", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "shop_id", required = false) @Nullable UUID shopId,
        @Parameter(name = "actor", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "actor", required = false) @Nullable UUID actor,
        @Parameter(name = "action", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "action", required = false) @Nullable String action
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "[ { \"actor_user_id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"shop_id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"action\" : \"action\", \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"entity_id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"meta_json\" : \"{}\", \"entity\" : \"entity\", \"ts\" : \"2000-01-23T04:56:07.000+00:00\" }, { \"actor_user_id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"shop_id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"action\" : \"action\", \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"entity_id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"meta_json\" : \"{}\", \"entity\" : \"entity\", \"ts\" : \"2000-01-23T04:56:07.000+00:00\" } ]";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_ADMIN_SHOPS_POST = "/admin/shops";
    /**
     * POST /admin/shops : Create shop (Admin)
     *
     * @return Created (status code 201)
     */
    @Operation(
        operationId = "adminShopsPost",
        summary = "Create shop (Admin)",
        responses = {
            @ApiResponse(responseCode = "201", description = "Created", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Shop.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = AdminApi.PATH_ADMIN_SHOPS_POST,
        produces = { "application/json" }
    )
    default ResponseEntity<Shop> adminShopsPost(
        
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"quota_json\" : \"{}\", \"name\" : \"name\", \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"plan\" : \"plan\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_ADMIN_SHOPS_SHOP_ID_PATCH = "/admin/shops/{shopId}";
    /**
     * PATCH /admin/shops/{shopId} : Update plan/status/quota for a shop (Admin)
     *
     * @param shopId  (required)
     * @param adminShopPatch  (required)
     * @return Updated (status code 200)
     */
    @Operation(
        operationId = "adminShopsShopIdPatch",
        summary = "Update plan/status/quota for a shop (Admin)",
        responses = {
            @ApiResponse(responseCode = "200", description = "Updated")
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.PATCH,
        value = AdminApi.PATH_ADMIN_SHOPS_SHOP_ID_PATCH,
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> adminShopsShopIdPatch(
        @NotNull @Parameter(name = "shopId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("shopId") UUID shopId,
        @Parameter(name = "AdminShopPatch", description = "", required = true) @Valid @RequestBody AdminShopPatch adminShopPatch
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
