/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.17.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.api;

import org.openapitools.model.Bill;
import org.openapitools.model.BillsBillIdPayPostRequest;
import java.util.UUID;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-11-02T12:30:08.264664900+07:00[Asia/Saigon]", comments = "Generator version: 7.17.0")
@Validated
@Tag(name = "bills", description = "the bills API")
public interface BillsApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    String PATH_BILLS_BILL_ID_PAY_POST = "/bills/{billId}/pay";
    /**
     * POST /bills/{billId}/pay : Pay a bill
     *
     * @param billId  (required)
     * @param billsBillIdPayPostRequest  (required)
     * @return Paid (status code 200)
     */
    @Operation(
        operationId = "billsBillIdPayPost",
        summary = "Pay a bill",
        responses = {
            @ApiResponse(responseCode = "200", description = "Paid")
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = BillsApi.PATH_BILLS_BILL_ID_PAY_POST,
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> billsBillIdPayPost(
        @NotNull @Parameter(name = "billId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("billId") UUID billId,
        @Parameter(name = "BillsBillIdPayPostRequest", description = "", required = true) @Valid @RequestBody BillsBillIdPayPostRequest billsBillIdPayPostRequest
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_BILLS_BILL_ID_PRINT_POST = "/bills/{billId}/print";
    /**
     * POST /bills/{billId}/print : Print bill via ESC/POS
     *
     * @param billId  (required)
     * @return Printed (status code 200)
     */
    @Operation(
        operationId = "billsBillIdPrintPost",
        summary = "Print bill via ESC/POS",
        responses = {
            @ApiResponse(responseCode = "200", description = "Printed")
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = BillsApi.PATH_BILLS_BILL_ID_PRINT_POST
    )
    default ResponseEntity<Void> billsBillIdPrintPost(
        @NotNull @Parameter(name = "billId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("billId") UUID billId
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_BILLS_BILL_ID_SPLIT_POST = "/bills/{billId}/split";
    /**
     * POST /bills/{billId}/split : Split a bill
     *
     * @param billId  (required)
     * @return Split OK (status code 200)
     */
    @Operation(
        operationId = "billsBillIdSplitPost",
        summary = "Split a bill",
        responses = {
            @ApiResponse(responseCode = "200", description = "Split OK")
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = BillsApi.PATH_BILLS_BILL_ID_SPLIT_POST
    )
    default ResponseEntity<Void> billsBillIdSplitPost(
        @NotNull @Parameter(name = "billId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("billId") UUID billId
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_BILLS_POST = "/bills";
    /**
     * POST /bills : Create bill
     *
     * @param bill  (required)
     * @return Created (status code 201)
     */
    @Operation(
        operationId = "billsPost",
        summary = "Create bill",
        responses = {
            @ApiResponse(responseCode = "201", description = "Created")
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = BillsApi.PATH_BILLS_POST,
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> billsPost(
        @Parameter(name = "Bill", description = "", required = true) @Valid @RequestBody Bill bill
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
