/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.17.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.api;

import org.springframework.lang.Nullable;
import org.openapitools.model.Product;
import java.util.UUID;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-11-02T12:30:08.264664900+07:00[Asia/Saigon]", comments = "Generator version: 7.17.0")
@Validated
@Tag(name = "products", description = "the products API")
public interface ProductsApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    String PATH_PRODUCTS_GET = "/products";
    /**
     * GET /products : List products by shop
     *
     * @param shopId  (optional)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "productsGet",
        summary = "List products by shop",
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Product.class)))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = ProductsApi.PATH_PRODUCTS_GET,
        produces = { "application/json" }
    )
    default ResponseEntity<List<Product>> productsGet(
        @Parameter(name = "shop_id", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "shop_id", required = false) @Nullable UUID shopId
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "[ { \"shop_id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"uom\" : \"uom\", \"cost\" : 6.027456183070403, \"price\" : 0.8008281904610115, \"stock_qty\" : 1.4658129805029452, \"name\" : \"name\", \"active\" : true, \"min_stock\" : 5.962133916683182, \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"sku\" : \"sku\", \"category\" : \"category\", \"tax_rate\" : 5.637376656633329 }, { \"shop_id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"uom\" : \"uom\", \"cost\" : 6.027456183070403, \"price\" : 0.8008281904610115, \"stock_qty\" : 1.4658129805029452, \"name\" : \"name\", \"active\" : true, \"min_stock\" : 5.962133916683182, \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"sku\" : \"sku\", \"category\" : \"category\", \"tax_rate\" : 5.637376656633329 } ]";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_PRODUCTS_POST = "/products";
    /**
     * POST /products : Create product (Owner)
     *
     * @param product  (required)
     * @return Created (status code 201)
     */
    @Operation(
        operationId = "productsPost",
        summary = "Create product (Owner)",
        responses = {
            @ApiResponse(responseCode = "201", description = "Created")
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ProductsApi.PATH_PRODUCTS_POST,
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> productsPost(
        @Parameter(name = "Product", description = "", required = true) @Valid @RequestBody Product product
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
