/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.17.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.api;

import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.lang.Nullable;
import org.openapitools.model.OccupancyReport;
import java.time.OffsetDateTime;
import org.openapitools.model.RevenueReport;
import org.openapitools.model.StockValueReport;
import java.util.UUID;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-11-02T12:30:08.264664900+07:00[Asia/Saigon]", comments = "Generator version: 7.17.0")
@Validated
@Tag(name = "reports", description = "the reports API")
public interface ReportsApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    String PATH_REPORTS_OCCUPANCY_GET = "/reports/occupancy";
    /**
     * GET /reports/occupancy : Occupancy report
     *
     * @param shopId  (optional)
     * @param from  (optional)
     * @param to  (optional)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "reportsOccupancyGet",
        summary = "Occupancy report",
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = OccupancyReport.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = ReportsApi.PATH_REPORTS_OCCUPANCY_GET,
        produces = { "application/json" }
    )
    default ResponseEntity<OccupancyReport> reportsOccupancyGet(
        @Parameter(name = "shop_id", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "shop_id", required = false) @Nullable UUID shopId,
        @Parameter(name = "from", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "from", required = false) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME) @Nullable OffsetDateTime from,
        @Parameter(name = "to", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "to", required = false) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME) @Nullable OffsetDateTime to
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"slots\" : [ { \"occupancy_pct\" : 0.8008281904610115, \"slot\" : \"slot\" }, { \"occupancy_pct\" : 0.8008281904610115, \"slot\" : \"slot\" } ] }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_REPORTS_REVENUE_GET = "/reports/revenue";
    /**
     * GET /reports/revenue : Revenue report
     *
     * @param shopId  (optional)
     * @param from  (optional)
     * @param to  (optional)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "reportsRevenueGet",
        summary = "Revenue report",
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = RevenueReport.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = ReportsApi.PATH_REPORTS_REVENUE_GET,
        produces = { "application/json" }
    )
    default ResponseEntity<RevenueReport> reportsRevenueGet(
        @Parameter(name = "shop_id", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "shop_id", required = false) @Nullable UUID shopId,
        @Parameter(name = "from", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "from", required = false) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME) @Nullable OffsetDateTime from,
        @Parameter(name = "to", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "to", required = false) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME) @Nullable OffsetDateTime to
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"totals_by_day\" : [ { \"revenue\" : 0.8008281904610115, \"day\" : \"2000-01-23\" }, { \"revenue\" : 0.8008281904610115, \"day\" : \"2000-01-23\" } ], \"from\" : \"2000-01-23T04:56:07.000+00:00\", \"to\" : \"2000-01-23T04:56:07.000+00:00\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_REPORTS_STOCKVALUE_GET = "/reports/stockvalue";
    /**
     * GET /reports/stockvalue : Stock value report
     *
     * @param shopId  (optional)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "reportsStockvalueGet",
        summary = "Stock value report",
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = StockValueReport.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = ReportsApi.PATH_REPORTS_STOCKVALUE_GET,
        produces = { "application/json" }
    )
    default ResponseEntity<StockValueReport> reportsStockvalueGet(
        @Parameter(name = "shop_id", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "shop_id", required = false) @Nullable UUID shopId
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"total_value\" : 0.8008281904610115, \"by_category\" : [ { \"category\" : \"category\", \"value\" : 6.027456183070403 }, { \"category\" : \"category\", \"value\" : 6.027456183070403 } ] }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
