/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.17.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.api;

import org.openapitools.model.OpenSession;
import org.openapitools.model.Session;
import org.openapitools.model.SessionsSessionIdPatchRequest;
import java.util.UUID;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-11-02T12:30:08.264664900+07:00[Asia/Saigon]", comments = "Generator version: 7.17.0")
@Validated
@Tag(name = "sessions", description = "the sessions API")
public interface SessionsApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    String PATH_SESSIONS_POST = "/sessions";
    /**
     * POST /sessions : Open session (POS)
     *
     * @param openSession  (required)
     * @return Created (status code 201)
     */
    @Operation(
        operationId = "sessionsPost",
        summary = "Open session (POS)",
        responses = {
            @ApiResponse(responseCode = "201", description = "Created", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Session.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = SessionsApi.PATH_SESSIONS_POST,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Session> sessionsPost(
        @Parameter(name = "OpenSession", description = "", required = true) @Valid @RequestBody OpenSession openSession
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"shop_id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"end_at\" : \"2000-01-23T04:56:07.000+00:00\", \"computed_fee\" : 6.027456183070403, \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"state\" : \"OPEN\", \"table_id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"start_at\" : \"2000-01-23T04:56:07.000+00:00\", \"pause_total_s\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_SESSIONS_SESSION_ID_PATCH = "/sessions/{sessionId}";
    /**
     * PATCH /sessions/{sessionId} : Pause/Resume/Transfer/Close session (POS)
     *
     * @param sessionId  (required)
     * @param sessionsSessionIdPatchRequest  (required)
     * @return Updated (status code 200)
     */
    @Operation(
        operationId = "sessionsSessionIdPatch",
        summary = "Pause/Resume/Transfer/Close session (POS)",
        responses = {
            @ApiResponse(responseCode = "200", description = "Updated")
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.PATCH,
        value = SessionsApi.PATH_SESSIONS_SESSION_ID_PATCH,
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> sessionsSessionIdPatch(
        @NotNull @Parameter(name = "sessionId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("sessionId") UUID sessionId,
        @Parameter(name = "SessionsSessionIdPatchRequest", description = "", required = true) @Valid @RequestBody SessionsSessionIdPatchRequest sessionsSessionIdPatchRequest
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
