/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.17.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.api;

import org.openapitools.model.CreateStaff;
import org.openapitools.model.PaymentSession;
import java.util.UUID;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-11-02T12:30:08.264664900+07:00[Asia/Saigon]", comments = "Generator version: 7.17.0")
@Validated
@Tag(name = "shops", description = "the shops API")
public interface ShopsApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    String PATH_SHOPS_SHOP_ID_STAFF_POST = "/shops/{shopId}/staff";
    /**
     * POST /shops/{shopId}/staff : Invite/create staff under a shop (Owner)
     *
     * @param shopId  (required)
     * @param createStaff  (required)
     * @return Created (status code 201)
     */
    @Operation(
        operationId = "shopsShopIdStaffPost",
        summary = "Invite/create staff under a shop (Owner)",
        responses = {
            @ApiResponse(responseCode = "201", description = "Created")
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ShopsApi.PATH_SHOPS_SHOP_ID_STAFF_POST,
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> shopsShopIdStaffPost(
        @NotNull @Parameter(name = "shopId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("shopId") UUID shopId,
        @Parameter(name = "CreateStaff", description = "", required = true) @Valid @RequestBody CreateStaff createStaff
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_SHOPS_SHOP_ID_UPGRADE_POST = "/shops/{shopId}/upgrade";
    /**
     * POST /shops/{shopId}/upgrade : Start upgrade to Premium (Owner)
     *
     * @param shopId  (required)
     * @return Payment session created (status code 200)
     */
    @Operation(
        operationId = "shopsShopIdUpgradePost",
        summary = "Start upgrade to Premium (Owner)",
        responses = {
            @ApiResponse(responseCode = "200", description = "Payment session created", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = PaymentSession.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ShopsApi.PATH_SHOPS_SHOP_ID_UPGRADE_POST,
        produces = { "application/json" }
    )
    default ResponseEntity<PaymentSession> shopsShopIdUpgradePost(
        @NotNull @Parameter(name = "shopId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("shopId") UUID shopId
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"checkout_url\" : \"checkout_url\", \"session_id\" : \"session_id\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
