/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.17.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.api;

import org.springframework.lang.Nullable;
import org.openapitools.model.Table;
import java.util.UUID;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-11-02T12:30:08.264664900+07:00[Asia/Saigon]", comments = "Generator version: 7.17.0")
@Validated
@Tag(name = "tables", description = "the tables API")
public interface TablesApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    String PATH_TABLES_GET = "/tables";
    /**
     * GET /tables : List tables by shop
     *
     * @param shopId  (optional)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "tablesGet",
        summary = "List tables by shop",
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Table.class)))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = TablesApi.PATH_TABLES_GET,
        produces = { "application/json" }
    )
    default ResponseEntity<List<Table>> tablesGet(
        @Parameter(name = "shop_id", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "shop_id", required = false) @Nullable UUID shopId
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "[ { \"area\" : \"area\", \"shop_id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"code\" : \"code\", \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"type\" : \"POOL\", \"status\" : \"IDLE\" }, { \"area\" : \"area\", \"shop_id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"code\" : \"code\", \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"type\" : \"POOL\", \"status\" : \"IDLE\" } ]";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_TABLES_POST = "/tables";
    /**
     * POST /tables : Create table (Owner)
     *
     * @param table  (required)
     * @return Created (status code 201)
     */
    @Operation(
        operationId = "tablesPost",
        summary = "Create table (Owner)",
        responses = {
            @ApiResponse(responseCode = "201", description = "Created")
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = TablesApi.PATH_TABLES_POST,
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> tablesPost(
        @Parameter(name = "Table", description = "", required = true) @Valid @RequestBody Table table
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_TABLES_TABLE_ID_PATCH = "/tables/{tableId}";
    /**
     * PATCH /tables/{tableId} : Update table (Owner)
     *
     * @param tableId  (required)
     * @return Updated (status code 200)
     */
    @Operation(
        operationId = "tablesTableIdPatch",
        summary = "Update table (Owner)",
        responses = {
            @ApiResponse(responseCode = "200", description = "Updated")
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.PATCH,
        value = TablesApi.PATH_TABLES_TABLE_ID_PATCH
    )
    default ResponseEntity<Void> tablesTableIdPatch(
        @NotNull @Parameter(name = "tableId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("tableId") UUID tableId
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
